### ISSUE TITLE
Issues From Playtesting

### ISSUE THREAD

**Issue by bjpaupor** [HuskyGameDev/2020s-team9#309]
Add pirates to level with dagger (probably 1-2)
More spike pits and scenery in levels (in general)
Spikes in the inescapable pit (1-3)
~~Flatland Fight should be easier~~
Map entering levels to something other than movement
Small graphical errors in the tiles of the levels (Should search through them at the end)
Warning about water and how it's safe to traverse
~~Attacking in mid-air~~
Level 2-2 zoom fix
1-3 final edge should be a mountain/cliff
Non-ordinary start for access to all levels
~~Pause menu not working in World 2~~

**Comment by CrystalSpore** [comment]
Fixed pause menu in world 2

**Comment by bjpaupor** [comment]
Fixed air attacks (a bit buggy, but functional)

**Comment by bjpaupor** [comment]
Flatland level should be a bit more balanced with new enemy AI
